SUPERNET:
  MLP_RATIO: [8.5, 8.5, 4.5, 4.5]
  NUM_HEADS: [1, 3, 6, 8]
  EMBED_DIM: [32, 96, 192, 256]
  DEPTH: [3, 3, 3, 3]
  KERNEL_SIZE: [5, 5, 5, 5]
  CONV_CHOICE: [0, 1, 2, 3, 4]
  
SEARCH_SPACE:
  MLP_RATIO:
    - -1
    - -0.5
    - 0
  EMBED_DIM:
    - -64
    - -32
    - 0
  DEPTH:
    - -1
    - -2
    - 0
  KERNEL_SIZE:
    - -2
    - -2
